language: c
rvm:
  - 2.3

cache: ccache

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      rvm: system

env:
  global:
    - HOMEBREW_DEVELOPER=1

before_install:
  - brew update || brew update
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - mkdir -p $(brew --repo)/Library/Taps/${TRAVIS_REPO_SLUG%/*}
  - ln -s $PWD $(brew --repo)/Library/Taps/${TRAVIS_REPO_SLUG}
  - cd $(brew --repo)/Library/Taps/${TRAVIS_REPO_SLUG}
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/${TRAVIS_REPO_SLUG}"
  - ulimit -n 1024
  # Fix linux error: Incorrect file permissions (664)
  - chmod 0644 Formula/*.rb
  - umask 022

script:
  - brew test-bot --no-bottle

notifications:
  email:
    on_success: never
    on_failure: always
